# Generated by Django 2.1.7 on 2019-03-10 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketcore', '0003_product_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('send_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='From', to='marketcore.User')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='To', to='marketcore.User')),
            ],
            options={
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/products_imgs/noname/nn.jpg', upload_to='imgs/'),
        ),
    ]
